/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cliente;

import clientermidao.DaoLogin;
import java.awt.Image;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.ImageIcon;
import mundo.Paciente;

/**
 *
 * @author joburbanop
 */
public class EditarPaciente extends javax.swing.JFrame {
    
    
    private static EditarPaciente pacienteEditar;
    private Paciente pacienAEditar;
    private PacienteInterfaz paciente;
    
    /**
     * Creates new form EditarPaciente
     */
    public EditarPaciente() {
        initComponents();
        super.setTitle("Editar Datos Paciente"); // titulo
        super.setSize(600, 300);// tamaño ventana
        super.setLocationRelativeTo(null);// posicion en el centro de la pantalla
        paceinteEditar();
        imagen();
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFielNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFielCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFielEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxSangre = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel3.setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(52, 199, 89));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Guardar cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.PAGE_END);
        jPanel1.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1);

        jTextFielNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielNombreActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFielNombre);

        jLabel4.setText("Cedula:");
        jPanel2.add(jLabel4);
        jPanel2.add(jTextFielCedula);

        jLabel3.setText("Email:");
        jPanel2.add(jLabel3);
        jPanel2.add(jTextFielEmail);

        jLabel2.setText("Tipo de  sangre");
        jPanel2.add(jLabel2);

        jComboBoxSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));
        jPanel2.add(jComboBoxSangre);

        jPanel3.add(jPanel2);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFielNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try{
         
            Registry registro=LocateRegistry.getRegistry("127.0.0.1",7777);
            DaoLogin interfaz = (DaoLogin) registro.lookup("RemotoRMI");
            pacienAEditar=interfaz.pacienteLogeado();
            interfaz.editarDatos(jTextFielCedula.getText(), jTextFielNombre.getText(), jComboBoxSangre.getSelectedItem().toString(),jTextFielEmail.getText() );
            super.setVisible(false);
            paciente =new PacienteInterfaz();
            paciente.setVisible(true);
        }catch(Exception e){
            System.out.println("estamos en excepcion dentro de paceinte"+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public static EditarPaciente getPacienteEditar(){
        if(pacienteEditar==null)
            pacienteEditar=new EditarPaciente();
        
        return pacienteEditar;
    }
    
    public void paceinteEditar() {
        try{
         
            Registry registro=LocateRegistry.getRegistry("127.0.0.1",7777);
            DaoLogin interfaz = (DaoLogin) registro.lookup("RemotoRMI");
            pacienAEditar=interfaz.pacienteLogeado();
            jTextFielNombre.setText(pacienAEditar.getNombre());
            jTextFielCedula.setText(pacienAEditar.getCedula());
            jTextFielEmail.setText(pacienAEditar.getEmail());
            jComboBoxSangre.setSelectedItem(pacienAEditar.getTipoDeSangre());
            
        }catch(Exception e){
            System.out.println("estamos en excepcion dentro de paceinte"+e);
        }
        
   }
   public void imagen(){
    

    ImageIcon imagenLoguin = new ImageIcon(getClass().getResource("/imagenes/logo.png"));
    jLabel5.setIcon(new ImageIcon(imagenLoguin.getImage().getScaledInstance(400,
                400, Image.SCALE_SMOOTH)));
    
    
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxSangre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFielCedula;
    private javax.swing.JTextField jTextFielEmail;
    private javax.swing.JTextField jTextFielNombre;
    // End of variables declaration//GEN-END:variables
}
