/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cliente;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
/**
 *
 * @author joburbanop
 */
public class Login extends javax.swing.JFrame {
     /*
     *Atributos 
     */
    private static Login login;
    private int indice = 0;
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        CambianteLabel(jLabelCambiante);
        quitarFondo ();
        imagen();
        texto();
        Font font = new Font("Roboto", Font.PLAIN, 12);
        super.setTitle("Agendar Citas"); // titulo
        super.setFont(font);
        super.setSize(900, 500);// tamaño ventana
        super.setLocationRelativeTo(null);// posicion en el centro de la pantalla
        super.setBackground(new Color(100, 129, 140));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        PanelImagenRol = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelImagen = new javax.swing.JLabel();
        PanelBotones = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        textoRol1 = new javax.swing.JLabel();
        jLabelCambiante = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonDoctor = new javax.swing.JButton();
        jButtonPaciente = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabelTmanio = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jSliderTamañoLetra = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(52, 199, 89));
        PanelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        PanelImagenRol.setBackground(new java.awt.Color(52, 199, 89));
        PanelImagenRol.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(52, 199, 89));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        labelImagen.setBackground(new java.awt.Color(52, 199, 89));
        labelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelImagen);

        PanelImagenRol.add(jPanel2);

        jPanel1.add(PanelImagenRol);

        PanelBotones.setBackground(new java.awt.Color(52, 199, 89));
        PanelBotones.setLayout(new java.awt.GridLayout(3, 2, 20, 50));

        jPanel4.setBackground(new java.awt.Color(52, 199, 89));
        jPanel4.setLayout(new java.awt.GridLayout(2, 0));
        PanelBotones.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(52, 199, 89));
        jPanel5.setLayout(new java.awt.GridLayout(2, 0));

        textoRol1.setFont(new java.awt.Font("FreeSans", 3, 18)); // NOI18N
        textoRol1.setForeground(new java.awt.Color(255, 255, 255));
        textoRol1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoRol1.setText("Tu lugar de confianza");
        textoRol1.setToolTipText("");
        jPanel5.add(textoRol1);

        jLabelCambiante.setBackground(new java.awt.Color(52, 199, 89));
        jLabelCambiante.setFont(new java.awt.Font("FreeSans", 3, 14)); // NOI18N
        jLabelCambiante.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCambiante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCambiante.setText("Conce mas de MediControl");
        jPanel5.add(jLabelCambiante);

        PanelBotones.add(jPanel5);

        jPanel3.setBackground(new java.awt.Color(52, 199, 89));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButtonDoctor.setBackground(new java.awt.Color(52, 199, 89));
        jButtonDoctor.setToolTipText("");
        jButtonDoctor.setIconTextGap(10);
        jButtonDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoctorActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDoctor);

        jButtonPaciente.setBackground(new java.awt.Color(52, 199, 89));
        jButtonPaciente.setInheritsPopupMenu(true);
        jButtonPaciente.setOpaque(true);
        jButtonPaciente.setSelected(true);
        jButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacienteActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPaciente);

        PanelBotones.add(jPanel3);

        jPanel1.add(PanelBotones);

        PanelPrincipal.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBackground(new java.awt.Color(52, 199, 89));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabelTmanio.setFont(new java.awt.Font("FreeSans", 3, 18)); // NOI18N
        jLabelTmanio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTmanio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTmanio.setText("Escoge el tamaño de texto");
        jPanel6.add(jLabelTmanio);

        jPanel9.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(52, 199, 89));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jSliderTamañoLetra.setBackground(new java.awt.Color(255, 255, 255));
        jSliderTamañoLetra.setForeground(new java.awt.Color(255, 255, 255));
        jSliderTamañoLetra.setMajorTickSpacing(5);
        jSliderTamañoLetra.setMaximum(30);
        jSliderTamañoLetra.setMinimum(10);
        jSliderTamañoLetra.setPaintLabels(true);
        jSliderTamañoLetra.setPaintTicks(true);
        jSliderTamañoLetra.setValue(20);
        jSliderTamañoLetra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderTamañoLetraStateChanged(evt);
            }
        });
        jPanel7.add(jSliderTamañoLetra);

        jPanel9.add(jPanel7);

        PanelPrincipal.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(PanelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDoctorActionPerformed

    private void jSliderTamañoLetraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderTamañoLetraStateChanged
       int fontSize = jSliderTamañoLetra.getValue();
        Font font = textoRol1.getFont();
        textoRol1.setFont(new Font(font.getName(), font.getStyle(), fontSize));
        jLabelTmanio.setFont(new Font(font.getName(), font.getStyle(), fontSize));
        jLabelCambiante.setFont(new Font(font.getName(), font.getStyle(), fontSize));
    }//GEN-LAST:event_jSliderTamañoLetraStateChanged

    private void jButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacienteActionPerformed
        super.setVisible(false);
        RolPaciente paciente=RolPaciente.getRolPaciente();
        paciente.setVisible(true);
    }//GEN-LAST:event_jButtonPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    public void quitarFondo (){
        jButtonPaciente.setOpaque(false);
        
        jButtonDoctor.setOpaque(false);
    }
    
    public void CambianteLabel(JLabel jLabelCambiante) {
        this.jLabelCambiante = jLabelCambiante;
        startTimer();
    }
    
    private void startTimer() {
        String[] textos = {"Si eres paciente","Controla tu salud", "En MediControl, puedes agendar citas.", "Si eres doctor ", "Historial de pacientes", "Citas del dia","Manejo agenda"};
        
        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Actualiza el texto del JLabel aquí
                
                jLabelCambiante.setText(textos[indice]);
                indice=indice+1;
                if(indice==textos.length)
                    indice=0;
            }
        });
        timer.start();
    }
    /**
 * Método que establece la imagen del Login y de los botones Paciente y Doctor.
*/
public void imagen(){
    

    ImageIcon imagenLoguin = new ImageIcon(getClass().getResource("/imagenes/logo.png"));
    labelImagen.setIcon(new ImageIcon(imagenLoguin.getImage().getScaledInstance(400,
                400, Image.SCALE_SMOOTH)));
    
    
    ImageIcon imagenPaciente = new ImageIcon(getClass().getResource("/imagenes/estetoscopio.png"));
    jButtonPaciente.setIcon(new ImageIcon(imagenPaciente.getImage().getScaledInstance(100,
                100, Image.SCALE_SMOOTH)));
    
    ImageIcon imagenDoctor = new ImageIcon(getClass().getResource("/imagenes/iconLogin.jpg"));
    jButtonDoctor.setIcon(new ImageIcon(imagenDoctor.getImage().getScaledInstance(100,
                100, Image.SCALE_SMOOTH)));
    
}
/**
     * singleton Patrones de login 
     * de esta forma se garantiza que la clase teanga una sola intancia 
     * @return intancia de login
     */
    public static Login getLogin(){
        if(login==null)
            login=new Login();
        
        return login;
    }

/**
 * Setea la fuente de los componentes de texto en la interfaz.
 * Utiliza la fuente Roboto de tamaño 20.
 */

public void texto(){
    Font font = new Font("Roboto", Font.PLAIN, 20);
    
    jButtonDoctor.setFont(font);
    jButtonPaciente.setFont(font);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelImagenRol;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton jButtonDoctor;
    private javax.swing.JButton jButtonPaciente;
    private javax.swing.JLabel jLabelCambiante;
    private javax.swing.JLabel jLabelTmanio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSlider jSliderTamañoLetra;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel textoRol1;
    // End of variables declaration//GEN-END:variables
}
