/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package cliente;

import clientermidao.DaoLogin;
import java.awt.Color;
import java.awt.Image;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mundo.Paciente;

/**
 *
 * @author joburbanop
 */
public class PacienteInterfaz extends javax.swing.JFrame {
    
    private static PacienteInterfaz pacienteInterfaz;
    private RolPaciente pacienteRol; 
    private Paciente pacienteLog;

    /** Creates new form PacienteInterfaz */
    public PacienteInterfaz() {
        initComponents();
        super.setTitle("Pacientes"); // titulo
        super.setSize(900, 500);// tamaño ventana
        super.setLocationRelativeTo(null);// posicion en el centro de la pantalla
        
        imagen();
        pacienteRol = RolPaciente.getRolPaciente();
        System.out.print("hola");
        //jTextFieldNombres  getNombres
        
        //jLabelEmail.setText(pacienteLog.getCedula());
        paceinteLogeado();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButtonCitasHistorial = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButtonCitasHistorial1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButtonCitasHistorial2 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jButtonCitasHistorial3 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButtonCitasHistorial4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jPanel5 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelTipoDeSangre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel11.setBackground(new java.awt.Color(52, 199, 89));
        jPanel11.setLayout(new java.awt.GridLayout(5, 0));

        jPanel16.setBackground(new java.awt.Color(52, 199, 89));
        jPanel16.setLayout(new java.awt.GridBagLayout());

        jButtonCitasHistorial.setBackground(new java.awt.Color(52, 199, 89));
        jButtonCitasHistorial.setFont(new java.awt.Font("FreeSans", 3, 15)); // NOI18N
        jButtonCitasHistorial.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCitasHistorial.setText("- Historial de citas");
        jButtonCitasHistorial.setPreferredSize(new java.awt.Dimension(183, 23));
        jButtonCitasHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitasHistorialActionPerformed(evt);
            }
        });
        jPanel16.add(jButtonCitasHistorial, new java.awt.GridBagConstraints());

        jPanel11.add(jPanel16);

        jPanel14.setBackground(new java.awt.Color(52, 199, 89));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        jButtonCitasHistorial1.setBackground(new java.awt.Color(52, 199, 89));
        jButtonCitasHistorial1.setFont(new java.awt.Font("FreeSans", 3, 15)); // NOI18N
        jButtonCitasHistorial1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCitasHistorial1.setText("- Agendar citas");
        jButtonCitasHistorial1.setPreferredSize(new java.awt.Dimension(183, 23));
        jButtonCitasHistorial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitasHistorial1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 70, 21, 71);
        jPanel14.add(jButtonCitasHistorial1, gridBagConstraints);

        jPanel11.add(jPanel14);

        jPanel13.setBackground(new java.awt.Color(52, 199, 89));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        jButtonCitasHistorial2.setBackground(new java.awt.Color(52, 199, 89));
        jButtonCitasHistorial2.setFont(new java.awt.Font("FreeSans", 3, 15)); // NOI18N
        jButtonCitasHistorial2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCitasHistorial2.setText("- Medicos disponibles");
        jButtonCitasHistorial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitasHistorial2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 70, 21, 71);
        jPanel13.add(jButtonCitasHistorial2, gridBagConstraints);

        jPanel11.add(jPanel13);

        jPanel12.setBackground(new java.awt.Color(52, 199, 89));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        jButtonCitasHistorial3.setBackground(new java.awt.Color(52, 199, 89));
        jButtonCitasHistorial3.setFont(new java.awt.Font("FreeSans", 3, 15)); // NOI18N
        jButtonCitasHistorial3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCitasHistorial3.setText("- Medicamentos ");
        jButtonCitasHistorial3.setPreferredSize(new java.awt.Dimension(183, 23));
        jButtonCitasHistorial3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitasHistorial3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 70, 21, 71);
        jPanel12.add(jButtonCitasHistorial3, gridBagConstraints);

        jPanel11.add(jPanel12);

        jPanel15.setBackground(new java.awt.Color(52, 199, 89));
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        jButtonCitasHistorial4.setBackground(new java.awt.Color(52, 199, 89));
        jButtonCitasHistorial4.setFont(new java.awt.Font("FreeSans", 3, 15)); // NOI18N
        jButtonCitasHistorial4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCitasHistorial4.setText("Editar tus datos");
        jButtonCitasHistorial4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitasHistorial4ActionPerformed(evt);
            }
        });
        jPanel15.add(jButtonCitasHistorial4);

        jPanel11.add(jPanel15);

        jPanel2.add(jPanel11);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("FreeSans", 3, 14)); // NOI18N
        jLabel8.setText("Tu informacion");
        jPanel9.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new java.awt.GridLayout(2, 2, 50, 50));

        jLabel9.setText("Email : ");
        jPanel19.add(jLabel9);
        jPanel19.add(jLabelEmail);

        jLabel11.setText("Cedula: ");
        jPanel19.add(jLabel11);
        jPanel19.add(jLabelCedula);

        jPanel9.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel18, java.awt.BorderLayout.CENTER);

        jLabel7.setFont(new java.awt.Font("FreeSans", 3, 14)); // NOI18N
        jLabel7.setText("Familiares ");
        jPanel10.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel10);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jPanel6.setBackground(new java.awt.Color(52, 199, 89));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel1);

        jPanel3.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(52, 199, 89));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("FreeSans", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Bienvenido");
        jPanel7.add(jLabel2);

        jPanel3.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(52, 199, 89));
        jPanel8.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setFont(new java.awt.Font("FreeSans", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cambia el tamaño de letra");
        jPanel8.add(jLabel3);

        jSlider1.setForeground(new java.awt.Color(255, 255, 255));
        jSlider1.setMajorTickSpacing(5);
        jSlider1.setMaximum(30);
        jSlider1.setMinimum(10);
        jSlider1.setPaintLabels(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(20);
        jPanel8.add(jSlider1);

        jPanel3.add(jPanel8);

        jPanel5.setBackground(new java.awt.Color(52, 199, 89));
        jPanel5.setLayout(new java.awt.GridLayout(3, 0));

        jLabelNombre.setFont(new java.awt.Font("FreeSans", 3, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Hola ");
        jPanel5.add(jLabelNombre);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("--------------------------------------");
        jPanel5.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("FreeSans", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Informacion");
        jPanel5.add(jLabel5);

        jPanel3.add(jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jLabel6.setFont(new java.awt.Font("FreeSans", 3, 14)); // NOI18N
        jLabel6.setText("Tipo de sangre");
        jPanel4.add(jLabel6);

        jLabelTipoDeSangre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabelTipoDeSangre);

        jPanel3.add(jPanel4);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCitasHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitasHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCitasHistorialActionPerformed

    private void jButtonCitasHistorial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitasHistorial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCitasHistorial1ActionPerformed

    private void jButtonCitasHistorial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitasHistorial2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCitasHistorial2ActionPerformed

    private void jButtonCitasHistorial3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitasHistorial3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCitasHistorial3ActionPerformed

    private void jButtonCitasHistorial4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitasHistorial4ActionPerformed
        super.setVisible(false);
        EditarPaciente paciente=EditarPaciente.getPacienteEditar();
        paciente.setVisible(true);
    }//GEN-LAST:event_jButtonCitasHistorial4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        super.setVisible(false);
        RolPaciente rol= RolPaciente.getRolPaciente();
        rol.setVisible(true);   
    }//GEN-LAST:event_jButton1ActionPerformed

    //jLabel1
    public void imagen(){
    

    ImageIcon imagenLoguin = new ImageIcon(getClass().getResource("/imagenes/estetoscopio.png"));
    jLabel1.setIcon(new ImageIcon(imagenLoguin.getImage().getScaledInstance(80,
                80, Image.SCALE_SMOOTH)));
    

}
    /**
     * Singleton de PacienteInterfaz
     * Devuelve una instancia de la clase PacienteInterfaz, si no existe la crea.
     * @return una instancia de la clase PacienteInterfaz.
    */
   public static PacienteInterfaz getPacienteInterfaz(){
        if(pacienteInterfaz==null)
            pacienteInterfaz=new PacienteInterfaz();
        
        return pacienteInterfaz;
    }

   public void paceinteLogeado() {
        try{
            Registry registro=LocateRegistry.getRegistry("127.0.0.1",7777);
            DaoLogin interfaz = (DaoLogin) registro.lookup("RemotoRMI");
            pacienteLog=interfaz.pacienteLogeado();
            jLabelEmail.setText(pacienteLog.getEmail());
            jLabelCedula.setText(pacienteLog.getCedula());
            jLabelTipoDeSangre.setText(pacienteLog.getTipoDeSangre());
            jLabelNombre.setText(jLabelNombre.getText()+ pacienteLog.getNombre());
        }catch(Exception e){
            System.out.println("estamos en excepcion dentro de paceinte"+e);
        }
        
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCitasHistorial;
    private javax.swing.JButton jButtonCitasHistorial1;
    private javax.swing.JButton jButtonCitasHistorial2;
    private javax.swing.JButton jButtonCitasHistorial3;
    private javax.swing.JButton jButtonCitasHistorial4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTipoDeSangre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables

}
