/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cliente;


import clientermidao.DaoLogin;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;
import mundo.Cifrado;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.ImageIcon;


import mundo.Paciente;

/**
 *
 * @author joburbanop
 */
public class Registro extends javax.swing.JFrame {
    
    private static Registro pacienteAregistrar;

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        imagen();
        Font font = new Font("Roboto", Font.PLAIN, 12);
        super.setTitle("Registrar Pacientes"); // titulo
        super.setFont(font);
        super.setSize(900, 500);// tamaño ventana
        super.setLocationRelativeTo(null);// posicion en el centro de la pantalla
        super.setBackground(new Color(100, 129, 140));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EntradaNombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EntradaSangre = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        EntradaEmail = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        EntradaCedula = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel8.setBackground(new java.awt.Color(52, 199, 89));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));
        jPanel8.add(jLabel5);

        getContentPane().add(jPanel8);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(6, 0));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel6);

        jPanel1.add(jPanel9);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        EntradaNombre.setText("Nombres y apellidos....");
        EntradaNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntradaNombreMouseClicked(evt);
            }
        });
        EntradaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 186;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 16, 10);
        jPanel2.add(EntradaNombre, gridBagConstraints);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Tipo de sangre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        EntradaSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));
        EntradaSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaSangreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 148;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 43, 20, 13);
        jPanel3.add(EntradaSangre, gridBagConstraints);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 73;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel4.add(jLabel3, gridBagConstraints);

        EntradaEmail.setText("example@gmail.com...");
        EntradaEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntradaEmailMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 186;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 16, 10);
        jPanel4.add(EntradaEmail, gridBagConstraints);

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Cedula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel5.add(jLabel4, gridBagConstraints);

        EntradaCedula.setText("1086...");
        EntradaCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntradaCedulaMouseClicked(evt);
            }
        });
        EntradaCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaCedulaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 186;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 16, 10);
        jPanel5.add(EntradaCedula, gridBagConstraints);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO code application logic here
        try{
            Registry registro=LocateRegistry.getRegistry("127.0.0.1",7777);
            DaoLogin interfaz = (DaoLogin) registro.lookup("RemotoRMI");

            //System.out.println("aca si");
           // Crear un nuevo objeto Paciente y establecer sus valores
            
            System.out.println(EntradaNombre.getText());
            System.out.println(EntradaEmail.getText());
            System.out.println(EntradaCedula.getText());
            if(!interfaz.verificarUsuario(EntradaNombre.getText(), EntradaCedula.getText())){
                Paciente nuevoPaciente = new Paciente();
                nuevoPaciente.setNombre(EntradaNombre.getText());
                nuevoPaciente.setTipoDeSangre(EntradaSangre.getSelectedItem().toString());
                nuevoPaciente.setEmail(EntradaEmail.getText());
                nuevoPaciente.setCedula(EntradaCedula.getText());
                interfaz.agregar(nuevoPaciente);
                interfaz.agregarEnArchivo(nuevoPaciente);
                JOptionPane.showMessageDialog(null, "El paciente fue registrado correctamente.");
            }else{
                JOptionPane.showMessageDialog(null, "Paciente ya se ha registrado o faltan datos");
 
            }

        }catch(Exception e){
            System.out.println("estamos en excepcion"+e);
        }
    
        

        
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        super.setVisible(false);
        RolPaciente rol= RolPaciente.getRolPaciente();
        rol.setVisible(true);                              
    }//GEN-LAST:event_jButton3ActionPerformed

    private void EntradaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaNombreActionPerformed

    private void EntradaCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaCedulaActionPerformed

    private void EntradaNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntradaNombreMouseClicked
        EntradaNombre.setText("");
    }//GEN-LAST:event_EntradaNombreMouseClicked

    private void EntradaEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntradaEmailMouseClicked
        EntradaEmail.setText("");
    }//GEN-LAST:event_EntradaEmailMouseClicked

    private void EntradaCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntradaCedulaMouseClicked
        EntradaCedula.setText("");
    }//GEN-LAST:event_EntradaCedulaMouseClicked

    private void EntradaSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaSangreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaSangreActionPerformed

    
    /**
     * @param args the command line arguments
     */
    //jLabel5

    public void imagen(){
    

    ImageIcon imagenLoguin = new ImageIcon(getClass().getResource("/imagenes/logo.png"));
    jLabel5.setIcon(new ImageIcon(imagenLoguin.getImage().getScaledInstance(400,
                400, Image.SCALE_SMOOTH)));
    
    ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/registro-medico.png"));
    jLabel6.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(80,
                80, Image.SCALE_SMOOTH)));
   
    
}
    /**
     * singleton de Registro 
     * de esta forma se garantiza que la clase teanga una sola intancia 
     * @return intancia de login
     */
    public static Registro getRegistro(){
        if(pacienteAregistrar==null)
            pacienteAregistrar=new Registro();
        
        return pacienteAregistrar;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EntradaCedula;
    private javax.swing.JTextField EntradaEmail;
    private javax.swing.JTextField EntradaNombre;
    private javax.swing.JComboBox<String> EntradaSangre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
