/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cliente;

import clientermidao.DaoLogin;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mundo.Paciente;

/**
 *
 * @author joburbanop
 */
public class RolPaciente extends javax.swing.JFrame {
    
    private static RolPaciente pacienteRol;
    
    private Login rol;
    
    static RolPaciente getRolPaciente() {
        if(pacienteRol==null)
            pacienteRol=new RolPaciente();
        
        return pacienteRol;
    }

    /**
     * Creates new form RolPaciente
     */
    public RolPaciente() {
        initComponents();
        rol=new Login();
        imagen();
        super.setTitle("Rol paciente"); // titulo
        super.setSize(900, 500);// tamaño ventana
        super.setLocationRelativeTo(null);// posicion en el centro de la pantalla
        super.setBackground(new Color(100, 129, 140));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        PanelImagenRol = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelImagen = new javax.swing.JLabel();
        PanelBotones = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabelCedula = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(52, 199, 89));
        PanelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        PanelImagenRol.setBackground(new java.awt.Color(52, 199, 89));
        PanelImagenRol.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(52, 199, 89));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        labelImagen.setBackground(new java.awt.Color(52, 199, 89));
        labelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelImagen);

        PanelImagenRol.add(jPanel2);

        jPanel1.add(PanelImagenRol);

        PanelBotones.setBackground(new java.awt.Color(52, 199, 89));
        PanelBotones.setLayout(new java.awt.GridLayout(3, 2, 20, 50));

        jPanel4.setBackground(new java.awt.Color(52, 199, 89));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 0, 10));

        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabelImagen);

        PanelBotones.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(52, 199, 89));
        jPanel5.setLayout(new java.awt.GridLayout(2, 0));

        jPanel8.setBackground(new java.awt.Color(52, 199, 89));
        jPanel8.setLayout(new java.awt.GridLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel8.add(jLabel2);

        jTextFieldNombre.setText("Nombre...");
        jTextFieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldNombreMousePressed(evt);
            }
        });
        jPanel8.add(jTextFieldNombre);

        jPanel5.add(jPanel8);

        jPanel10.setBackground(new java.awt.Color(52, 199, 89));
        jPanel10.setLayout(new java.awt.GridLayout(1, 2));

        jLabelCedula.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel10.add(jLabelCedula);

        jTextFieldCedula.setText("Cedula...");
        jTextFieldCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCedulaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldCedulaMousePressed(evt);
            }
        });
        jPanel10.add(jTextFieldCedula);

        jPanel5.add(jPanel10);

        PanelBotones.add(jPanel5);

        jPanel3.setBackground(new java.awt.Color(52, 199, 89));
        jPanel3.setLayout(new java.awt.GridLayout());

        jButton2.setBackground(new java.awt.Color(52, 199, 89));
        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setBackground(new java.awt.Color(52, 199, 89));
        jButton3.setText("Iniciar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        PanelBotones.add(jPanel3);

        jPanel1.add(PanelBotones);

        PanelPrincipal.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBackground(new java.awt.Color(52, 199, 89));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));
        jPanel9.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(52, 199, 89));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));
        jPanel9.add(jPanel7);

        PanelPrincipal.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(jButtonRegresar, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(PanelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        super.setVisible(false);
        rol= Login.getLogin();
        rol.setVisible(true); 
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jTextFieldCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCedulaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldCedulaMouseClicked

    private void jTextFieldNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNombreMousePressed
        // TODO add your handling code here:
        jTextFieldNombre.setText("");
    }//GEN-LAST:event_jTextFieldNombreMousePressed

    private void jTextFieldCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCedulaMousePressed
        // TODO add your handling code here:
        jTextFieldCedula.setText("");
    }//GEN-LAST:event_jTextFieldCedulaMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        super.setVisible(false);
        Registro rol= Registro.getRegistro();
        rol.setVisible(true);    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Registry registro=LocateRegistry.getRegistry("127.0.0.1",7777);
            DaoLogin interfaz = (DaoLogin) registro.lookup("RemotoRMI");

            
            if(interfaz.verificarUsuario(jTextFieldNombre.getText(), jTextFieldCedula.getText())){
                super.setVisible(false);
                PacienteInterfaz rol= PacienteInterfaz.getPacienteInterfaz();
                rol.setVisible(true); 
                
            }else{
                JOptionPane.showMessageDialog(null, "Paciente no registrado");
 
            }

        }catch(Exception e){
            System.out.println("estamos en excepcion"+e);
        }
    
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public void imagen(){
    
        ImageIcon imagenLoguin = new ImageIcon(getClass().getResource("/imagenes/logo.png"));
        labelImagen.setIcon(new ImageIcon(imagenLoguin.getImage().getScaledInstance(400,
                400, Image.SCALE_SMOOTH)));
        
        ImageIcon imagenInicio=new ImageIcon(getClass().getResource("/imagenes/registro-medico.png"));
        jLabelImagen.setIcon(new ImageIcon(imagenInicio.getImage().getScaledInstance(100,
                100, Image.SCALE_SMOOTH)));
        
        
        ImageIcon imagenL2 = new ImageIcon(getClass().getResource("/imagenes/iconLogin.jpg"));
        jLabel2.setIcon(new ImageIcon(imagenL2.getImage().getScaledInstance(50,
                50, Image.SCALE_SMOOTH))); 
         
        ImageIcon imagenL3 = new ImageIcon(getClass().getResource("/imagenes/candado.png"));
        jLabelCedula.setIcon(new ImageIcon(imagenL3.getImage().getScaledInstance(50,
                50, Image.SCALE_SMOOTH)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelImagenRol;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JLabel labelImagen;
    // End of variables declaration//GEN-END:variables
}
